default_language_version:
  python: python3

repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: "v2.3.1"
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff
        stages: [pre-commit]
      - id: ruff
        name: sort imports with ruff
        args: [--select, I, --fix]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: debug-statements
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-ast
        stages: [pre-commit]
      - id: check-builtin-literals
        stages: [pre-commit]
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/PyCQA/flake8
    rev: "7.3.0"
    hooks:
      - id: flake8
        args: [--config=.flake8]
        additional_dependencies:
          [
            "git+https://github.com/RedHatQE/flake8-plugins.git@v0.0.10",
            "flake8-mutable",
            "pep8-naming",
          ]
        stages: [pre-commit]

  - repo: https://github.com/jorisroovers/gitlint
    rev: "v0.19.1"
    hooks:
      - id: gitlint
        stages: [commit-msg]

  - repo: https://github.com/gitleaks/gitleaks
    rev: "v8.28.0"
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        exclude: "test_(.*).py$"
        additional_dependencies:
          [
            "types-PyYAML",
            "types-requests",
            "types-paramiko",
            "types-beautifulsoup4",
            "pytest",
            "types-xmltodict",
            "types-setuptools",
            "types-pexpect",
            "types-netaddr",
          ]
